services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT:-{{cookiecutter.app_port_host}}}:{{cookiecutter.internal_app_port}}"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      - statsd
      - jaeger
      - loki
    networks:
      - app_network
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app_network
  statsd:
    image: prom/statsd-exporter:latest
    ports:
      - "8125:8125/udp"
      - "9102:9102"
    restart: unless-stopped
    networks:
      - app_network
  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"   # UI
      - "14268:14268"   # HTTP collector
      - "4317:4317"     # gRPC collector
      - "5778:5778"     # Agent HTTP (опционально)
      - "14250:14250"   # gRPC для агент-сборщика
    restart: unless-stopped
    networks:
      - app_network
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
